IS_not_position_VPT: false
aa: rand-m9-mstd0.5-inc1
amp: false
batch_size: 64
cfg: /data1/sw99/NOAH/experiments/VPT/ViT-B_prompt_vpt_5.yaml
change_qkv: false
clip_grad: null
color_jitter: 0.4
cooldown_epochs: 10
cutmix: 1.0
cutmix_minmax: null
data_path: ./data/dataset/oxford_pets
data_set: oxford_pets-FS
decay_epochs: 30
decay_rate: 0.1
device: cuda
direct_resize: false
dist_eval: false
dist_url: env://
distributed: false
drop: 0.0
drop_block: null
drop_path: 0.1
drop_rate_LoRA: 0.1
drop_rate_adapter: 0.1
drop_rate_prompt: 0.1
epochs: 300
eval: false
few_shot_seed: 0
few_shot_shot: 2
gp: false
inat_category: name
inception: false
input_size: 224
is_LoRA: false
is_adapter: false
is_prefix: false
is_visual_prompt_tuning: false
launcher: none
lr: 0.0005
lr_noise: null
lr_noise_pct: 0.67
lr_noise_std: 1.0
lr_power: 1.0
max_relative_position: 14
min_lr: 1.0e-05
mixup: 0.8
mixup_mode: batch
mixup_prob: 1.0
mixup_switch_prob: 0.5
mode: super
model: ''
model_ema: false
model_ema_decay: 0.99996
model_ema_force_cpu: false
momentum: 0.9
no_abs_pos: false
no_aug: false
num_workers: 10
opt: adamw
opt_betas: null
opt_eps: 1.0e-08
output_dir: './eval/few-shot_oxford_pets_shot-8_seed-2_lr-0.005_wd-0.0001_VPT_5 '
patch_size: 16
patience_epochs: 10
pin_mem: true
platform: pai
post_norm: false
recount: 1
relative_position: false
remode: pixel
repeated_aug: false
reprob: 0.25
resplit: false
resume: /data1/sw99/ViT-B_16.npz
rpe_type: bias
sched: cosine
seed: 0
smoothing: 0.1
start_epoch: 0
teacher_model: ''
train_interpolation: bicubic
val_interval: 10
warmup_epochs: 10
warmup_lr: 1.0e-06
weight_decay: 0.05
world_size: 1
